table PizzaOrders
	lineageTag: eff61bec-c3de-466d-b505-5c08a2d520d9

	measure 'Order Count' = DISTINCTCOUNT(PizzaOrders[Order ID])
		formatString: #,0
		displayFolder: BISM2202 Measures
		lineageTag: dad2ae41-7c06-494b-8c8c-65fe8e6aed38

	measure 'Avg Delivery Duration' = AVERAGE(PizzaOrders[Delivery Duration (min)])
		formatString: 0.00
		displayFolder: BISM2202 Measures
		lineageTag: 3681cff0-975d-4e7d-8bf4-bc75b802cdfd

	measure 'Avg Toppings Count' = AVERAGE(PizzaOrders[Toppings Count])
		formatString: 0.00
		displayFolder: BISM2202 Measures
		lineageTag: 4ac20d0a-404f-4119-b7fc-df17af742eb1

	measure 'Avg Delay' = AVERAGE(PizzaOrders[Delay (min)])
		formatString: 0.00
		displayFolder: BISM2202 Measures
		lineageTag: 288a95d4-3fff-4db6-b8d7-fc43390f5015

	measure 'Avg Topping Density' = AVERAGE(PizzaOrders[Topping Density])
		formatString: 0.000
		displayFolder: BISM2202 Measures
		lineageTag: 48285af4-b2c8-4a4e-982e-695b0d3e07b2

	measure 'Delivery Duration Color' = VAR CurrentValue = [Avg Delivery Duration] VAR MinValue = MINX(ALL(PizzaOrders[Restaurant Name]), CALCULATE([Avg Delivery Duration])) VAR MaxValue = MAXX(ALL(PizzaOrders[Restaurant Name]), CALCULATE([Avg Delivery Duration])) RETURN SWITCH(TRUE(), CurrentValue = MinValue, "#BFE3E0", CurrentValue = MaxValue, "#F4A261", "#E9EEF3")
		displayFolder: BISM2202 Helpers
		lineageTag: 562afef0-77ee-41e9-9d31-253a347fbce1

	measure 'Delay Color' = VAR CurrentValue = [Avg Delay] VAR MinValue = MINX(ALL(PizzaOrders[Restaurant Name]), CALCULATE([Avg Delay])) VAR MaxValue = MAXX(ALL(PizzaOrders[Restaurant Name]), CALCULATE([Avg Delay])) RETURN SWITCH(TRUE(), CurrentValue = MinValue, "#CDE8F6", CurrentValue = MaxValue, "#E76F51", "#EEF1F4")
		displayFolder: BISM2202 Helpers
		lineageTag: 03255a6d-d468-4437-8dad-afe66ce54167

	measure 'Order Share Within Payment' = DIVIDE([Order Count], CALCULATE([Order Count], REMOVEFILTERS(PizzaOrders[Traffic Level])))
		formatString: 0.00%
		displayFolder: BISM2202 Measures
		lineageTag: c79ecd5d-3e40-490a-9bd3-be3a052c9f26

	measure 'Order Share Overall' = DIVIDE([Order Count], CALCULATE([Order Count], REMOVEFILTERS(PizzaOrders)))
		formatString: 0.00%
		displayFolder: BISM2202 Measures
		lineageTag: 567f3398-0b47-49ae-a28c-6216109631a7

	measure 'Total Orders KPI' = [Order Count]
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 3072e786-9c53-56b7-9a14-5855ecc3a2e7

	measure 'Unique Locations KPI' = DISTINCTCOUNT(PizzaOrders[Location])
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 158a115d-ad77-5efa-bdd8-c4b655422d9c

	measure 'Top Location Orders KPI' = MAXX(VALUES(PizzaOrders[Location]), CALCULATE([Order Count]))
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 5c254b81-5a20-5dfb-b4f7-5b72fef8ecc3

	measure 'Payment Methods KPI' = DISTINCTCOUNT(PizzaOrders[Payment Method])
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: f561577d-7ae0-5399-9bfc-b4450c422035

	measure 'Top Payment Orders KPI' = MAXX(VALUES(PizzaOrders[Payment Method]), CALCULATE([Order Count]))
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 87657c69-d0d7-52b6-b982-77be20cece09

	measure 'Highest Avg Delivery KPI' = MAXX(VALUES(PizzaOrders[Location]), CALCULATE([Avg Delivery Duration]))
		formatString: 0.00
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: b973aeb2-ad60-561c-a7cc-fff7aa8cf306

	measure 'Locations at Max Delivery KPI' = VAR M = [Highest Avg Delivery KPI] RETURN COUNTROWS(FILTER(VALUES(PizzaOrders[Location]), ABS(CALCULATE([Avg Delivery Duration]) - M) < 0.000001))
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: e15b3902-bc1d-5997-8a62-933266c863e4

	measure 'Overall Avg Delivery KPI' = [Avg Delivery Duration]
		formatString: 0.00
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 5b7ca915-b59e-548c-b8fc-38094abf93bb

	measure 'Peak Month Orders KPI' = MAXX(VALUES(PizzaOrders[Order Month Start]), CALCULATE([Order Count]))
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 5874f9a6-6ec7-51c8-803f-962b16b7836f

	measure 'Avg Monthly Orders KPI' = AVERAGEX(VALUES(PizzaOrders[Order Month Start]), CALCULATE([Order Count]))
		formatString: 0.00
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 861901de-8c64-55e3-9d5f-f9f84f029f48

	measure 'Latest Month Orders KPI' = VAR LatestMonth = MAX(PizzaOrders[Order Month Start]) RETURN CALCULATE([Order Count], PizzaOrders[Order Month Start] = LatestMonth)
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 5242f6b2-b77e-52f5-83dd-c9f1c3952ab8

	measure 'Peak Hour Orders KPI' = MAXX(VALUES(PizzaOrders[Order Hour]), CALCULATE([Order Count]))
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: bf6d005d-83e1-5b9a-baff-bc21cf6f03ec

	measure 'Peak Window Orders KPI' = CALCULATE([Order Count], FILTER(ALL(PizzaOrders[Order Hour]), PizzaOrders[Order Hour] >= 18 && PizzaOrders[Order Hour] <= 20))
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 73d830cc-56a8-5ab7-a055-c17eee614b0f

	measure 'Active Hours KPI' = COUNTROWS(FILTER(VALUES(PizzaOrders[Order Hour]), CALCULATE([Order Count]) > 0))
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 9d9c1a1e-9e67-5560-a95d-7dfafbbcaa83

	measure 'Dominant Complexity Share KPI' = MAXX(VALUES(PizzaOrders[Pizza Complexity]), CALCULATE([Order Share Overall]))
		formatString: 0.00%
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: c9e41af9-cb6e-52a2-83e8-e6eeb49eb6db

	measure 'Complexity Levels KPI' = DISTINCTCOUNT(PizzaOrders[Pizza Complexity])
		formatString: #,0
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: 6a733d2c-8465-54a2-be79-b21f19d5a2e2

	measure 'Avg Complexity KPI' = AVERAGE(PizzaOrders[Pizza Complexity])
		formatString: 0.00
		displayFolder: BISM2202 Dashboard KPIs
		lineageTag: da37454c-050b-5729-9f69-c716889220b5

	column 'Order ID'
		dataType: string
		lineageTag: b265fac1-1798-4f4d-b4c0-ffb9fe249d51
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Restaurant Name'
		dataType: string
		lineageTag: 26814635-153f-4ff1-a9a3-b35b979fbf3a
		summarizeBy: none
		sourceColumn: Restaurant Name

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 034ce043-f285-4f72-a52b-6bc4df3671ab
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Order Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: b7b96006-fa50-4ba2-ad14-1e0a9bf1507d
		summarizeBy: none
		sourceColumn: Order Time

		variation 变体
			isDefault
			relationship: 16209724-8ae8-4549-a96d-ef0a83945863
			defaultHierarchy: LocalDateTable_e1c4d522-349a-4535-9270-3aafe5f175f2.日期层次结构

		annotation SummarizationSetBy = Automatic

	column 'Delivery Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 663f1060-020d-4501-a88b-c4d46196b911
		summarizeBy: none
		sourceColumn: Delivery Time

		variation 变体
			isDefault
			relationship: 8aedf06a-8495-4614-8425-cf03fec80e17
			defaultHierarchy: LocalDateTable_4e0295f6-debf-4dac-b1e6-d4f1287cf88a.日期层次结构

		annotation SummarizationSetBy = Automatic

	column 'Delivery Duration (min)'
		dataType: int64
		formatString: 0
		lineageTag: fdc42460-cd4c-48e3-86d8-aef20445fe6b
		summarizeBy: sum
		sourceColumn: Delivery Duration (min)

		annotation SummarizationSetBy = Automatic

	column 'Pizza Size'
		dataType: string
		lineageTag: ade18f27-8280-461e-94a0-ed110d219949
		summarizeBy: none
		sourceColumn: Pizza Size

		annotation SummarizationSetBy = Automatic

	column 'Pizza Type'
		dataType: string
		lineageTag: 24512f5f-c9fa-43ca-9d18-19b83aba7a6a
		summarizeBy: none
		sourceColumn: Pizza Type

		annotation SummarizationSetBy = Automatic

	column 'Toppings Count'
		dataType: int64
		formatString: 0
		lineageTag: 0bb87e00-7c90-4be0-953a-6a07c127ac2d
		summarizeBy: sum
		sourceColumn: Toppings Count

		annotation SummarizationSetBy = Automatic

	column 'Distance (km)'
		dataType: double
		lineageTag: 22b53910-f881-4627-a7ed-ee58c93ba0b6
		summarizeBy: sum
		sourceColumn: Distance (km)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Traffic Level'
		dataType: string
		lineageTag: c79287c2-eb94-493b-bb58-c873c04215c1
		summarizeBy: none
		sourceColumn: Traffic Level

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: 390193ae-9b55-4731-827a-e6837a938bac
		summarizeBy: none
		sourceColumn: Payment Method

		annotation SummarizationSetBy = Automatic

	column 'Is Peak Hour'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 00b22b45-7cad-4713-a54c-34e59495b02c
		summarizeBy: none
		sourceColumn: Is Peak Hour

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 16ce1c06-539f-42da-9b0d-bd8e2ef71960
		summarizeBy: none
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	column 'Delivery Efficiency (min/km)'
		dataType: double
		lineageTag: 9566e31a-15bf-4af5-b8ea-4ba6a1a2bd7c
		summarizeBy: sum
		sourceColumn: Delivery Efficiency (min/km)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Topping Density'
		dataType: double
		lineageTag: 4a342850-cf86-488d-9d21-f8098dc14991
		summarizeBy: sum
		sourceColumn: Topping Density

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Month'
		dataType: string
		lineageTag: ba8c4db0-0acc-438e-8671-dd82c92df63a
		summarizeBy: none
		sourceColumn: Order Month

		annotation SummarizationSetBy = Automatic

	column 'Payment Category'
		dataType: string
		lineageTag: 6780e815-bb4d-40b3-bd4e-807d28363159
		summarizeBy: none
		sourceColumn: Payment Category

		annotation SummarizationSetBy = Automatic

	column 'Estimated Duration (min)'
		dataType: double
		lineageTag: ca03dcd0-58db-4043-9aad-fb1bcf873fd6
		summarizeBy: sum
		sourceColumn: Estimated Duration (min)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Delay (min)'
		dataType: double
		lineageTag: 1c124dfd-7a2b-4cf2-a9e2-2fb86499a298
		summarizeBy: sum
		sourceColumn: Delay (min)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Delayed'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d2d6e2a0-0296-45ec-a02c-283ddc8bf494
		summarizeBy: none
		sourceColumn: Is Delayed

		annotation SummarizationSetBy = Automatic

	column 'Pizza Complexity'
		dataType: int64
		formatString: 0
		lineageTag: 2ef8db75-24bc-4dba-b162-b3e9b5857598
		summarizeBy: sum
		sourceColumn: Pizza Complexity

		annotation SummarizationSetBy = Automatic

	column 'Traffic Impact'
		dataType: int64
		formatString: 0
		lineageTag: adaa3ec7-b378-4f3a-aae9-bd2cb71fc949
		summarizeBy: sum
		sourceColumn: Traffic Impact

		annotation SummarizationSetBy = Automatic

	column 'Order Hour'
		dataType: int64
		formatString: 0
		lineageTag: 8b65a2e1-4673-4e9c-89d5-ddd7a1e1d9b2
		summarizeBy: sum
		sourceColumn: Order Hour

		annotation SummarizationSetBy = Automatic

	column 'Restaurant Avg Time'
		dataType: double
		lineageTag: 6f14b459-ad85-4883-adcb-0cc3b99b5b97
		summarizeBy: sum
		sourceColumn: Restaurant Avg Time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weekend Label' = IF(PizzaOrders[Is Weekend] = TRUE(), "Weekend", "Weekday")
		dataType: string
		lineageTag: c03e1385-dcd7-4f1e-9a9a-ab37d5ce1306
		summarizeBy: none

	column 'Peak Hour Label' = IF(PizzaOrders[Is Peak Hour] = TRUE(), "Peak Hour", "Non-Peak Hour")
		dataType: string
		lineageTag: e1625a0f-a940-4d02-9d9e-113f42c3e2bd
		summarizeBy: none

	column 'Order Month Start' = DATE(YEAR(PizzaOrders[Order Time]), MONTH(PizzaOrders[Order Time]), 1)
		dataType: dateTime
		formatString: yyyy-MM
		lineageTag: df3dc216-1e55-41e3-9290-76fa3d30f74a
		summarizeBy: none

	column __OrderOne = 1
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a6ad1ede-d07c-4ea9-88fd-4cb7bda4cca8
		summarizeBy: sum

	column __LocationAvgDeliveryContribution = DIVIDE(CALCULATE(AVERAGE(PizzaOrders[Delivery Duration (min)]), ALLEXCEPT(PizzaOrders, PizzaOrders[Location])), CALCULATE(DISTINCTCOUNT(PizzaOrders[Order ID]), ALLEXCEPT(PizzaOrders, PizzaOrders[Location])))
		dataType: double
		isHidden
		lineageTag: 2660dfa4-538f-4397-8590-ad2aaaa235ac
		summarizeBy: sum

	column __RestaurantAvgDelayContribution = DIVIDE(CALCULATE(AVERAGE(PizzaOrders[Delay (min)]), ALLEXCEPT(PizzaOrders, PizzaOrders[Restaurant Name])), CALCULATE(DISTINCTCOUNT(PizzaOrders[Order ID]), ALLEXCEPT(PizzaOrders, PizzaOrders[Restaurant Name])))
		dataType: double
		isHidden
		lineageTag: 21cdd6c1-a468-417d-921f-d61c43a48995
		summarizeBy: sum

	column __PizzaTypeAvgDeliveryContribution = DIVIDE(CALCULATE(AVERAGE(PizzaOrders[Delivery Duration (min)]), ALLEXCEPT(PizzaOrders, PizzaOrders[Pizza Type])), CALCULATE(DISTINCTCOUNT(PizzaOrders[Order ID]), ALLEXCEPT(PizzaOrders, PizzaOrders[Pizza Type])))
		dataType: double
		isHidden
		lineageTag: 0c01deb2-6fe2-4557-b4fd-bc2ebdbbe28b
		summarizeBy: sum

	column 'Order Month English' = FORMAT(PizzaOrders[Order Month Start], "MMM yyyy", "en-US")
		dataType: string
		lineageTag: 95368a73-ff4d-42fb-a1ab-1bea19ae6c2d
		summarizeBy: none
		sortByColumn: 'Order Month Sort'

		changedProperty = SortByColumn

	column 'Order Month Sort' = YEAR(PizzaOrders[Order Month Start]) * 100 + MONTH(PizzaOrders[Order Month Start])
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2afc4a10-a058-4f72-a1a6-fd69f441b2d9
		summarizeBy: none

	partition PizzaOrders = m
		mode: import
		source =
				let
				    源 = Excel.Workbook(File.Contents("C:\BISM2202\INPUTS\Assignment1_BISM2202_pizza_sell_data.xlsx"), null, true),
				    Sheet1_Sheet = 源{[Item="Sheet1",Kind="Sheet"]}[Data],
				    提升的标题 = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"Order ID", type text}, {"Restaurant Name", type text}, {"Location", type text}, {"Order Time", type datetime}, {"Delivery Time", type datetime}, {"Delivery Duration (min)", Int64.Type}, {"Pizza Size", type text}, {"Pizza Type", type text}, {"Toppings Count", Int64.Type}, {"Distance (km)", type number}, {"Traffic Level", type text}, {"Payment Method", type text}, {"Is Peak Hour", type logical}, {"Is Weekend", type logical}, {"Delivery Efficiency (min/km)", type number}, {"Topping Density", type number}, {"Order Month", type text}, {"Payment Category", type text}, {"Estimated Duration (min)", type number}, {"Delay (min)", type number}, {"Is Delayed", type logical}, {"Pizza Complexity", Int64.Type}, {"Traffic Impact", Int64.Type}, {"Order Hour", Int64.Type}, {"Restaurant Avg Time", type number}}),
				    替换的值 = Table.ReplaceValue(更改的类型,"Marco’s Pizza","Marco's Pizza",Replacer.ReplaceText,{"Restaurant Name"})
				in
				    替换的值

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

